In [5]:
import pandas as pd

# Load RNA-RNA interaction file
file_path = "RNAInter_RNA_RNA.txt"

# Try common delimiters (RNAInter files are usually tab-delimited)
df = pd.read_csv(file_path, sep='\t', low_memory=False)

# Display basic info
print(f"Number of interactions: {len(df)}")
df.head()

Number of interactions: 9484609

,RNAInterID,Interactor1.Symbol,Category1,Species1,Interactor2.Symbol,Category2,Species2,Raw_ID1,Raw_ID2,score,strong,weak,predict
0,RR00000169,(Ca)N,repeats,Mus musculus,B1_Mus1,repeats,Mus musculus,chr4(CA)n125049227,chr15B1_Mus136600585,0.23,NaN,MARIO,NaN
1,RR00000238,(Ca)N,repeats,Mus musculus,B1_Mus1,repeats,Mus musculus,chr8(CA)n67899847,chr8B1_Mus167899573,0.23,NaN,MARIO,NaN
2,RR00000198,(Ca)N,repeats,Mus musculus,B1_Mus1,repeats,Mus musculus,chr6(CA)n135011645,chr6B1_Mus1135012241,0.23,NaN,MARIO,NaN
3,RR00000231,(Ca)N,repeats,Mus musculus,B1_Mus1,repeats,Mus musculus,chr8(CA)n114753246,chr8B1_Mus1114753067,0.23,NaN,MARIO,NaN
4,RR00000249,(Ca)N,repeats,Mus musculus,B3,repeats,Mus musculus,chr9(CA)n21755504,chr9B321755686,0.23,NaN,MARIO,NaN

In [6]:
# Show column names
print("Columns:", df.columns.tolist())

# Inspect data types
df.dtypes

Columns: ['RNAInterID', 'Interactor1.Symbol', 'Category1', 'Species1', 'Interactor2.Symbol', 'Category2', 'Species2', 'Raw_ID1', 'Raw_ID2', 'score', 'strong', 'weak', 'predict']

RNAInterID             object
Interactor1.Symbol     object
Category1              object
Species1               object
Interactor2.Symbol     object
Category2              object
Species2               object
Raw_ID1                object
Raw_ID2                object
score                 float64
strong                 object
weak                   object
predict                object
dtype: object

In [7]:
# Check unique categories in both interactors
cat1_unique = df['Category1'].unique()
cat2_unique = df['Category2'].unique()

# Optionally, combined unique categories across both columns
combined_categories = set(cat1_unique) | set(cat2_unique)
print("All unique RNA categories in dataset:", combined_categories)

All unique RNA categories in dataset: {'shRNA', 'tRNA', 'miRNA', 'unassigned RNA', 'rRNA', 'lncRNA', 'pseudo', 'tRF', 'antisense', 'eRNA', 'miscRNA', 'lincRNA', 'circRNA', 'ribozyme', 'snoRNA', 'scaRNA', 'unknown', 'protein', 'Category2', 'Category1', 'TR_C_gene', 'Protein', 'processed_transcript', 'piRNA', 'PCG', 'mRNA', 'TEC', 'repeats', 'sRNA', 'ncRNA', 'others', 'snRNA', 'scRNA', 'TF', 'sncRNA'}

In [8]:
df_mRNA = df[(df['Category1'] == 'mRNA') | (df['Category2'] == 'mRNA')]
print(f"Rows after keeping mRNA: {len(df_mRNA)}")

df_mRNA

Rows after keeping mRNA: 9253466

,RNAInterID,Interactor1.Symbol,Category1,Species1,Interactor2.Symbol,Category2,Species2,Raw_ID1,Raw_ID2,score,strong,weak,predict
98,RR00000081,(Ca)N,repeats,Mus musculus,Sacm1l,mRNA,Mus musculus,chr12(CA)n86725649,NCBI:83493,0.2300,NaN,MARIO,NaN
99,RR00000180,(Ca)N,repeats,Mus musculus,Sacm1l,mRNA,Mus musculus,chr5(CA)n113846835,NCBI:83493,0.2300,NaN,MARIO,NaN
100,RR00000167,(Ca)N,repeats,Mus musculus,Sacm1l,mRNA,Mus musculus,chr3(CA)n83375276,NCBI:83493,0.2300,NaN,MARIO,NaN
101,RR00000087,(Ca)N,repeats,Mus musculus,Sacm1l,mRNA,Mus musculus,chr13(CA)n29980063,NCBI:83493,0.2300,NaN,MARIO,NaN
102,RR00000216,(Ca)N,repeats,Mus musculus,Sacm1l,mRNA,Mus musculus,chr7(CA)n141447615,NCBI:83493,0.2300,NaN,MARIO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9484604,RR09489264,tRF-5046,tRF,Danio rerio,zzz3,mRNA,Danio rerio,tRFdb:tRF-5046,NCBI:567022,0.2131,NaN,NaN,RNAhybrid
9484605,RR09489265,tRF-5048,tRF,Danio rerio,zzz3,mRNA,Danio rerio,tRFdb:tRF-5048,NCBI:567022,0.3150,NaN,NaN,RNAhybrid//IntaRNA
9484606,RR09489266,tRF-5050,tRF,Danio rerio,zzz3,mRNA,Danio rerio,tRFdb:tRF-5050,NCBI:567022,0.3150,NaN,NaN,RNAhybrid//IntaRNA
9484607,RR09489267,tRF-5054,tRF,Danio rerio,zzz3,mRNA,Danio rerio,tRFdb:tRF-5054,NCBI:567022,0.2131,NaN,NaN,RNAhybrid
9484608,RR09489268,tRF-5057,tRF,Danio rerio,zzz3,mRNA,Danio rerio,tRFdb:tRF-5057,NCBI:567022,0.2131,NaN,NaN,RNAhybrid

In [9]:
exclude_categories = {'Category1', 'Category2', 'unknown', 'unassigned RNA', 'others', 'Protein', 'protein',
                      'PCG', # Protein-coding Gene
                      'TF', # transcription factor gene
                      'TR_C_gene', # T-cell receptor constant region gene; immune-related.
                      'antisense', # transcripts complementary to sense strands of annotated genes.
                      'TEC', # “to be experimentally confirmed,” provisional transcripts.
                      'repeats' # transcripts overlapping repetitive genomic elements.
                     }

# Filter out unwanted categories from both interactors
df_filt = df[~df['Category1'].isin(exclude_categories) & ~df['Category2'].isin(exclude_categories)]

print(f"Rows after removing not-clear categories: {len(df_filt)}")

Rows after removing not-clear categories: 9429474

In [10]:
# Check unique categories in both interactors
cat1_unique = df_filt['Category1'].unique()
cat2_unique = df_filt['Category2'].unique()

# Optionally, combined unique categories across both columns
combined_categories = set(cat1_unique) | set(cat2_unique)
print("All unique RNA categories in dataset:", combined_categories)

All unique RNA categories in dataset: {'shRNA', 'tRNA', 'miRNA', 'tRF', 'rRNA', 'pseudo', 'lncRNA', 'eRNA', 'miscRNA', 'lincRNA', 'circRNA', 'ribozyme', 'snoRNA', 'scaRNA', 'processed_transcript', 'piRNA', 'mRNA', 'sRNA', 'ncRNA', 'snRNA', 'scRNA', 'sncRNA'}

In [11]:
# filter nan
print(f"RNA–RNA interactions: {len(df_filt)}")
df_filt = df_filt.dropna(subset=['Raw_ID1', 'Raw_ID2'])
print(f"RNA–RNA interactions: {len(df_filt)}")

RNA–RNA interactions: 9429474
RNA–RNA interactions: 8976390

In [12]:
parsed = []

def parse_ids(id_value):
    if pd.isna(id_value):
        return [None]
    elif ':' in id_value:
        prefix, ids_str = id_value.split(':', 1)
        return [f"{prefix}:{id_.strip()}" for id_ in ids_str.split(';')]
    else:
        parsed.append(id_value)
        return [id_value.strip()]

# Add list columns
df_filt['Raw_ID1_list'] = df_filt['Raw_ID1'].apply(parse_ids)
df_filt['Raw_ID2_list'] = df_filt['Raw_ID2'].apply(parse_ids)

In [13]:
parsed

[]

In [14]:
print(f"RNA–RNA interactions: {len(df_filt)}")

RNA–RNA interactions: 8976390

In [15]:
df_filt.head()

,RNAInterID,Interactor1.Symbol,Category1,Species1,Interactor2.Symbol,Category2,Species2,Raw_ID1,Raw_ID2,score,strong,weak,predict,Raw_ID1_list,Raw_ID2_list
3638,RR00670755,Gm24029,snoRNA,Mus musculus,U5,snRNA,Mus musculus,Ensembl:ENSMUSG00000065862,Ensembl:ENSMUSG00000070228,0.23,NaN,MARIO,NaN,[Ensembl:ENSMUSG00000065862],[Ensembl:ENSMUSG00000070228]
3639,RR00670756,Gm24029,snoRNA,Mus musculus,U5,snRNA,Mus musculus,Ensembl:ENSMUSG00000065862,Ensembl:ENSMUSG00000075763,0.23,NaN,MARIO,NaN,[Ensembl:ENSMUSG00000065862],[Ensembl:ENSMUSG00000075763]
3640,RR00670754,Gm24029,snoRNA,Mus musculus,U5,snRNA,Mus musculus,Ensembl:ENSMUSG00000065862,Ensembl:ENSMUSG00000064881,0.23,NaN,MARIO,NaN,[Ensembl:ENSMUSG00000065862],[Ensembl:ENSMUSG00000064881]
3641,RR00673515,Gm24455,snoRNA,Mus musculus,U5,snRNA,Mus musculus,Ensembl:ENSMUSG00000065282,Ensembl:ENSMUSG00000064430,0.23,NaN,MARIO,NaN,[Ensembl:ENSMUSG00000065282],[Ensembl:ENSMUSG00000064430]
3642,RR00673516,Gm24455,snoRNA,Mus musculus,U5,snRNA,Mus musculus,Ensembl:ENSMUSG00000065282,Ensembl:ENSMUSG00000064881,0.23,NaN,MARIO,NaN,[Ensembl:ENSMUSG00000065282],[Ensembl:ENSMUSG00000064881]

In [16]:
# we need to standardise the species to TAXIDs

In [17]:
# 1. See unique species
df_filt.replace({'-': None}, inplace=True)
unique_species = pd.unique(df_filt[['Species1', 'Species2']].values.ravel())
print("Unique species:", len(unique_species))

from ete3 import NCBITaxa
ncbi = NCBITaxa()

unique_species_taxids = {}
missing = []

for test_species in unique_species:
    # Skip placeholders
    if test_species in [None]:
        continue

    # Handle known special cases first
    if test_species == 'Solanum tuberosum L.':
        unique_species_taxids[test_species] = "4113"
        continue
    if test_species == 'Rhodobacter sphaeroides ATCC 17025':
        unique_species_taxids[test_species] = "1061"
        continue

    # Query NCBI
    try:
        taxid = str(ncbi.get_name_translator([test_species])[test_species][0])
        unique_species_taxids[test_species] = taxid
    except KeyError:
        missing.append(test_species)

print("Mapped species (unique -1 for None):", len(unique_species_taxids))
print("Missing species:", missing)

Unique species: 98
Mapped species (unique -1 for None): 97
Missing species: []

In [18]:
# Assume df is your original dataframe
# unique_species_taxids: dict {species_name -> taxid}

df_filt['Species1_TaxID'] = df_filt['Species1'].map(unique_species_taxids)
df_filt['Species2_TaxID'] = df_filt['Species2'].map(unique_species_taxids)

unmapped_s1 = df_filt.loc[df_filt['Species1'].notna() & df_filt['Species1_TaxID'].isna(), 'Species1'].unique()
unmapped_s2 = df_filt.loc[df_filt['Species2'].notna() & df_filt['Species2_TaxID'].isna(), 'Species2'].unique()

print("Unmapped Species1:", unmapped_s1)
print("Unmapped Species2:", unmapped_s2)

Unmapped Species1: []
Unmapped Species2: []

In [19]:
# removing NAN
df_filt = df_filt.dropna(subset=['Species1_TaxID', 'Species2_TaxID'])

In [20]:
# Check unique categories in both interactors
cat1_unique = df_filt['Category1'].unique()
cat2_unique = df_filt['Category2'].unique()

# Optionally, combined unique categories across both columns
combined_categories = set(cat1_unique) | set(cat2_unique)
print("All unique RNA categories in dataset:", combined_categories)

RNA_TYPE_MAP = {
    'processed_transcript': 'ncRNA',
    'miscRNA': 'ncRNA',
}

# Apply standardisation
df_filt['Category1_std'] = df_filt['Category1'].replace(RNA_TYPE_MAP)
df_filt['Category2_std'] = df_filt['Category2'].replace(RNA_TYPE_MAP)

# Recompute unique categories after mapping
cat1_std = set(df_filt['Category1_std'].unique())
cat2_std = set(df_filt['Category2_std'].unique())

print("Standardised categories:", cat1_std | cat2_std)

assert not df_filt[['Category1_std', 'Category2_std']].isna().any().any()

All unique RNA categories in dataset: {'tRNA', 'miRNA', 'processed_transcript', 'tRF', 'rRNA', 'pseudo', 'lncRNA', 'piRNA', 'mRNA', 'miscRNA', 'sRNA', 'lincRNA', 'circRNA', 'ncRNA', 'ribozyme', 'snoRNA', 'scaRNA', 'snRNA', 'scRNA', 'sncRNA'}
Standardised categories: {'tRNA', 'miRNA', 'rRNA', 'pseudo', 'lncRNA', 'piRNA', 'tRF', 'mRNA', 'sRNA', 'lincRNA', 'circRNA', 'ncRNA', 'ribozyme', 'snoRNA', 'scaRNA', 'snRNA', 'scRNA', 'sncRNA'}

In [216]:
# Remove mRNA interactions at the beginning
df_filt = df_filt[
    (df_filt['Category1'] != 'mRNA') &
    (df_filt['Category2'] != 'mRNA')
].copy()

In [219]:
df_filt.keys()

Index(['RNAInterID', 'Interactor1.Symbol', 'Category1', 'Species1',
       'Interactor2.Symbol', 'Category2', 'Species2', 'Raw_ID1', 'Raw_ID2',
       'score', 'strong', 'weak', 'predict', 'Raw_ID1_list', 'Raw_ID2_list',
       'Species1_TaxID', 'Species2_TaxID', 'Category1_std', 'Category2_std',
       'Raw_ID1_key', 'Raw_ID2_key'],
      dtype='object')

In [220]:
# DATASET IS READY.
# df_filt keys: Index(['RNAInterID', 'Interactor1.Symbol', 'Category1', 'Species1',
#       'Interactor2.Symbol', 'Category2', 'Species2', 'Raw_ID1', 'Raw_ID2',
#       'score', 'strong', 'weak', 'predict', 'Raw_ID1_list', 'Raw_ID2_list'],
#      dtype='object')

'''
Index(['RNAInterID', 'Interactor1.Symbol', 'Category1', 'Species1',
       'Interactor2.Symbol', 'Category2', 'Species2', 'Raw_ID1', 'Raw_ID2',
       'score', 'strong', 'weak', 'predict', 'Raw_ID1_list', 'Raw_ID2_list',
       'Species1_TaxID', 'Species2_TaxID'],
      dtype='object')
'''

# Now we need to extract sequences, we start by taking unique of ('Interactor1.Symbol', 'Category1', 'Species1_TaxID', 'Raw_ID1_list')
# We do not care about 1 and 2, we can create the final database later.

def normalize_id_list(x):
    if isinstance(x, list):
        return tuple(sorted(str(i) for i in x if i is not None))
    return tuple()
df_filtbackup = df_filt

df_filt = df_filt.copy()
df_filt['Raw_ID1_key'] = df_filt['Raw_ID1_list'].apply(normalize_id_list)
df_filt['Raw_ID2_key'] = df_filt['Raw_ID2_list'].apply(normalize_id_list)

rna_entities_1 = (
    df_filt.loc[:, ['Interactor1.Symbol', 'Category1', 'Species1_TaxID', 'Raw_ID1_key']]
    .drop_duplicates()
    .rename(columns={
        'Interactor1.Symbol': 'Symbol',
        'Category1': 'Category',
        'Species1_TaxID': 'Species',
        'Raw_ID1_key': 'Raw_ID_key'
    })
)

rna_entities_2 = (
    df_filt.loc[:, ['Interactor2.Symbol', 'Category2', 'Species2_TaxID', 'Raw_ID2_key']]
    .drop_duplicates()
    .rename(columns={
        'Interactor2.Symbol': 'Symbol',
        'Category2': 'Category',
        'Species2_TaxID': 'Species',
        'Raw_ID2_key': 'Raw_ID_key'
    })
)

rna_entities = (
    pd.concat([rna_entities_1, rna_entities_2], ignore_index=True)
    .drop_duplicates()
)

print(f"Unique RNA entities: {len(rna_entities)}")

rna_entities['RNA_IDs'] = rna_entities['Raw_ID_key'].apply(list)

def classify_ids(id_list):
    return {
        'miRBase': [],
        'NCBI': [],
        'Ensembl': [],
        'circBase': [],
        'tRFdb': [],
        'GenBank': [],
        'Other': [],
        'RNAcentral': []   # ← to be filled after resolution
    }

def populate_buckets(id_list):
    buckets = classify_ids(id_list)
    for rid in id_list:
        if rid.startswith('miRBase:'):
            buckets['miRBase'].append(rid.split(':', 1)[1])
        elif rid.startswith('NCBI:'):
            buckets['NCBI'].append(rid.split(':', 1)[1])
        elif rid.startswith('Ensembl:'):
            buckets['Ensembl'].append(rid.split(':', 1)[1])
        elif rid.startswith('circBase:'):
            buckets['circBase'].append(rid.split(':', 1)[1])
        elif rid.startswith('tRFdb:'):
            buckets['tRFdb'].append(rid.split(':', 1)[1])
        elif rid.startswith('GenBank:'):
            buckets['GenBank'].append(rid.split(':', 1)[1])
        else:
            buckets['Other'].append(rid)
    return buckets

rna_entities['ID_buckets'] = rna_entities['RNA_IDs'].apply(populate_buckets)

Unique RNA entities: 29967

In [221]:
import pandas as pd

df_filt.to_pickle("interactions_processed_noRNAcentralIDs.pkl")

In [222]:
rna_entities

,Symbol,Category,Species,Raw_ID_key,RNA_IDs,ID_buckets
0,Gm24029,snoRNA,10090,"(Ensembl:ENSMUSG00000065862,)",[Ensembl:ENSMUSG00000065862],"{'miRBase': [], 'NCBI': [], 'Ensembl': ['ENSMU..."
1,Gm24455,snoRNA,10090,"(Ensembl:ENSMUSG00000065282,)",[Ensembl:ENSMUSG00000065282],"{'miRBase': [], 'NCBI': [], 'Ensembl': ['ENSMU..."
2,Gm24616,snoRNA,10090,"(Ensembl:ENSMUSG00000065208,)",[Ensembl:ENSMUSG00000065208],"{'miRBase': [], 'NCBI': [], 'Ensembl': ['ENSMU..."
3,Gm24888,snoRNA,10090,"(Ensembl:ENSMUSG00000077575,)",[Ensembl:ENSMUSG00000077575],"{'miRBase': [], 'NCBI': [], 'Ensembl': ['ENSMU..."
4,Gm26109,snoRNA,10090,"(Ensembl:ENSMUSG00000065904,)",[Ensembl:ENSMUSG00000065904],"{'miRBase': [], 'NCBI': [], 'Ensembl': ['ENSMU..."
...,...,...,...,...,...,...
34332,TCP10,pseudo,9606,"(NCBI:6953,)",[NCBI:6953],"{'miRBase': [], 'NCBI': ['6953'], 'Ensembl': [..."
34333,Vmn2r89,pseudo,10090,"(NCBI:22301,)",[NCBI:22301],"{'miRBase': [], 'NCBI': ['22301'], 'Ensembl': ..."
34334,ndst2a,pseudo,7955,"(NCBI:793524,)",[NCBI:793524],"{'miRBase': [], 'NCBI': ['793524'], 'Ensembl':..."
34335,ndufs8b,pseudo,7955,"(NCBI:554100,)",[NCBI:554100],"{'miRBase': [], 'NCBI': ['554100'], 'Ensembl':..."
34336,pcdh1g11,pseudo,7955,"(NCBI:553999,)",[NCBI:553999],"{'miRBase': [], 'NCBI': ['553999'], 'Ensembl':..."

In [223]:
from collections import defaultdict

# Initialize counter
db_counts = defaultdict(int)

for buckets in rna_entities['ID_buckets']:
    for db, ids in buckets.items():
        if db != 'RNAcentral':  # exclude placeholder
            db_counts[db] += len(set(ids))  # count unique IDs per entity

# Print summary
for db, count in db_counts.items():
    print(f"{db}: {count} unique IDs across entities")

miRBase: 6547 unique IDs across entities
NCBI: 19037 unique IDs across entities
Ensembl: 3886 unique IDs across entities
circBase: 255 unique IDs across entities
tRFdb: 261 unique IDs across entities
GenBank: 3 unique IDs across entities
Other: 0 unique IDs across entities

In [13]:
'''
To-discuss: Assumption: 
all annotated isoforms (transcripts) of a gene are considered potential interactors 
when RNAInter reports a gene-level interaction.

We could think of some filters on the isoforms. For now we download them all, and keep track of isoforms-per-interaction (A list of sequences)
'''

'\nTo-discuss: Assumption: \nall annotated isoforms (transcripts) of a gene are considered potential interactors \nwhen RNAInter reports a gene-level interaction.\n\nWe could think of some filters on the isoforms. For now we download them all, and keep track of isoforms-per-interaction (A list of sequences)\n'

<h3>Ensembl IDs to Ensemble transcripts to RNAcentral IDs</h3>

In [224]:
# Construct DUCK-DB based on RNAcentral BEFORE this step!!
import sys
sys.path.append("rnacentral-etl")

from rnacentral import QueryRnaCentral

qrc = QueryRnaCentral(base_dir="rnacentral_data/current_release", db_path="rnacentral-etl/rnacentral.duckdb")

In [225]:
'''
Adapt the code below based on the instructions:
Extract all RNAcentral IDS of the ensemble transcripts related to ensemble GeneIDs that satisfy the conditions (Tax ID and rna-type)
Extract from row.get("ID_buckets", {}).get("Ensembl", [])
and place in RNAcentral a list for each transcript, so that we have a list of lists. row.get("ID_buckets", {}).get("RNAcentral", [])

We are not sure if all ENSEMBL IDs we have are gene ids, so first try with gene, if nothing try with transcript ID.
'''

# Usefoul code: 
taxid= "10090"
res = qrc.ensembl_gene_to_rnacentral_transcripts("ENSMUSG00000065862", taxid) #for ENS. gene ID
# qrc.ensembl_to_rnacentral('ENSMUST00000083928', taxid) # ENSMUSG00000065862 for ENS transcript ID
'''
Ensure 'rna_type' returned by query rna central is the same rna_type of the row.
First look if the rnacentral type is in the standard categories: Standardised categories: {'tRNA', 'miRNA', 'rRNA', 'pseudo', 'lncRNA', 'piRNA', 'tRF', 'mRNA', 'sRNA', 'lincRNA', 'circRNA', 'ncRNA', 'ribozyme', 'snoRNA', 'scaRNA', 'snRNA', 'scRNA', 'sncRNA'}
If not print it because we need to standardise everything.
'''

res

   RNAcentral_ID rna_type  taxid external_db
0  URS0000639553   snoRNA  10090     ENSEMBL

In [226]:
STANDARD_RNA_TYPES = {
    "tRNA", "miRNA", "rRNA", "pseudo", "lncRNA", "piRNA", "tRF", "mRNA",
    "sRNA", "lincRNA", "circRNA", "ncRNA", "ribozyme", "snoRNA",
    "scaRNA", "snRNA", "scRNA", "sncRNA"
}


def get_rnacentral_ids(row):
    """
    Populate row['ID_buckets']['RNAcentral'] with:
    a list of lists (one list per Ensembl ID).
    """
    row = row.copy()
    id_buckets = row.get("ID_buckets", {})
    ensembl_ids = id_buckets.get("Ensembl", [])
    taxid = str(row.get("Species"))
    row_rna_type = row.get("Category")

    if not ensembl_ids or taxid is None:
        return row

    rnacentral_per_ensembl = []
    
    for ensembl_id in ensembl_ids:
        rnacentral_ids = set()

        try:
            # 1) try Ensembl gene → RNAcentral transcripts
            df = qrc.ensembl_gene_to_rnacentral_transcripts(
                ensembl_id, taxid
            )

            # 2) fallback: Ensembl transcript → RNAcentral
            if df is None or df.empty:
                df = qrc.ensembl_to_rnacentral(
                    ensembl_id, taxid
                )
                if df is not None and not df.empty:
                    print('Transcript detected')
                    print(df)

            if df is None or df.empty:
                continue

            for _, r in df.iterrows():
                rc_id = r.get("RNAcentral_ID")
                rc_type = r.get("rna_type")

                if pd.isna(rc_id) or pd.isna(rc_type):
                    print('rnacentral data not valid')
                    continue

                if rc_type not in STANDARD_RNA_TYPES:
                    print(f"[UNSTANDARDISED RNA TYPE] {rc_type}, row type in this case: {row_rna_type}")
                    continue

                if rc_type == row_rna_type:
                    rnacentral_ids.add(rc_id)
                else:
                    print(f"[NO TYPE MATCH] {rc_type}, row type in this case: {row_rna_type}")

        except Exception:
            continue

        if rnacentral_ids:
            rnacentral_per_ensembl.append(list(rnacentral_ids))

    id_buckets["RNAcentral"] = rnacentral_per_ensembl if rnacentral_per_ensembl else []
    row["ID_buckets"] = id_buckets

    return row


rna_entities_trial = rna_entities.apply(
    get_rnacentral_ids, axis=1
)

[NO TYPE MATCH] lncRNA, row type in this case: pseudo
[NO TYPE MATCH] lncRNA, row type in this case: pseudo
[NO TYPE MATCH] ncRNA, row type in this case: snRNA
[NO TYPE MATCH] ncRNA, row type in this case: snRNA
[NO TYPE MATCH] sRNA, row type in this case: miRNA
[NO TYPE MATCH] scaRNA, row type in this case: snoRNA
[NO TYPE MATCH] ncRNA, row type in this case: snRNA
[UNSTANDARDISED RNA TYPE] misc_RNA, row type in this case: snRNA

In [227]:
from collections import defaultdict
import numpy as np

# Collect all IDs and lengths
db_unique = defaultdict(set)
db_lengths = defaultdict(list)

for buckets in rna_entities_trial["ID_buckets"]:
    for db, ids in buckets.items():
        for x in ids:
            if isinstance(x, list):
                db_unique[db].update(x)
                db_lengths[db].append(len(x))
            else:
                db_unique[db].add(x)
                db_lengths[db].append(1)

# Summary
for db, ids in db_unique.items():
    lengths = db_lengths[db]
    if lengths:
        max_len = max(lengths)
        mean_len = np.mean(lengths)
        median_len = np.median(lengths)
    else:
        max_len = mean_len = median_len = 0

    print(f"{db}: {len(ids)} unique IDs across entities | "
          f"max list length: {max_len}, mean: {mean_len:.2f}, median: {median_len}")


from collections import defaultdict

# Collect list lengths per database
db_lengths = defaultdict(list)

for buckets in rna_entities_trial["ID_buckets"]:
    for db, ids in buckets.items():
        for x in ids:
            if isinstance(x, list):
                db_lengths[db].append(len(x))
            else:
                db_lengths[db].append(1)

# Compute counts per category
for db, lengths in db_lengths.items():
    count_1 = sum(1 for l in lengths if l == 1)
    count_2 = sum(1 for l in lengths if l == 2)
    count_3_10 = sum(1 for l in lengths if 3 <= l <= 10)
    count_gt10 = sum(1 for l in lengths if l > 10)

    print(f"{db}: 1={count_1}, 2={count_2}, 3-10={count_3_10}, >10={count_gt10}")


nonempty_rows = [len(buckets.get("RNAcentral", [])) for buckets in rna_entities_trial["ID_buckets"] if buckets.get("RNAcentral")]
print("Max sublists per non-empty row:", max(nonempty_rows))
print("Mean sublists per non-empty row:", np.mean(nonempty_rows))
print("Median sublists per non-empty row:", np.median(nonempty_rows))


# Iterate over rows and print the first few with non-empty RNAcentral
count_seq = 0
count_noseq = 0
for idx, row in rna_entities_trial.iterrows():
    rna_lists = row.get("ID_buckets", {}).get("RNAcentral", [])
    if rna_lists:  # only non-empty rows
        count_seq += 1
    else:
        count_noseq +=1
print(count_seq)
print(count_noseq)

Ensembl: 3886 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
RNAcentral: 10377 unique IDs across entities | max list length: 249, mean: 4.88, median: 1.0
NCBI: 18622 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
miRBase: 6365 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
circBase: 206 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
GenBank: 3 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
tRFdb: 242 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
Ensembl: 1=3886, 2=0, 3-10=0, >10=0
RNAcentral: 1=1378, 2=183, 3-10=352, >10=220
NCBI: 1=19037, 2=0, 3-10=0, >10=0
miRBase: 1=6547, 2=0, 3-10=0, >10=0
circBase: 1=255, 2=0, 3-10=0, >10=0
GenBank: 1=3, 2=0, 3-10=0, >10=0
tRFdb: 1=261, 2=0, 3-10=0, >10=0
Max sublists per non-empty row: 1
Mean sublists per non-empty row: 1.0
Median sublists per non-empty row: 1.0
2133
27834

In [228]:
import pandas as pd

rna_entities_trial.to_pickle("rna_entities_trial.pkl")

<h3>NCBI IDs to Ensembl IDs to Ensemble transcripts to RNAcentral IDs</h3>

In [304]:
import pandas as pd

STANDARD_RNA_TYPES = {
    "tRNA", "miRNA", "rRNA", "pseudo", "lncRNA", "piRNA", "tRF", "mRNA",
    "sRNA", "lincRNA", "circRNA", "ncRNA", "ribozyme", "snoRNA",
    "scaRNA", "snRNA", "scRNA", "sncRNA"
}

# Construct DUCK-DB based on RNAcentral BEFORE this step!!
import sys
sys.path.append("rnacentral-etl")

from rnacentral import QueryRnaCentral

qrc = QueryRnaCentral(base_dir="rnacentral_data/current_release", db_path="rnacentral-etl/rnacentral.duckdb")

AttributeError: 'QueryRnaCentral' object has no attribute 'mirbase_to_rnacentral'

In [229]:

import pandas as pd

rna_entities_trial = pd.read_pickle("rna_entities_trial.pkl")

In [230]:
# -----------------------------
# Load NCBI → Ensembl mapping
# -----------------------------
ncbi_to_ensemble = pd.read_csv(
    "gene2ensembl",
    sep="\t",
    dtype=str,
    comment="#",
    header=None,
    low_memory=False,
)

ncbi_to_ensemble.columns = [
    "taxid",
    "geneid",
    "ensembl_gene",
    "refseq_rna_version",
    "ensembl_transcript_id",
    "refseq_protein_version",
    "ensembl_protein_id",
]

# enforce string typing
ncbi_to_ensemble["taxid"] = ncbi_to_ensemble["taxid"].astype(str)
ncbi_to_ensemble["geneid"] = ncbi_to_ensemble["geneid"].astype(str)

In [231]:
# collect all GeneIDs used in your dataset
all_ncbi_ids = set()

for buckets in rna_entities_trial["ID_buckets"]:
    all_ncbi_ids.update(map(str, buckets.get("NCBI", [])))

print(f"{len(all_ncbi_ids)} unique NCBI GeneIDs")

18622 unique NCBI GeneIDs

In [232]:
ncbi_to_ensemble_small = ncbi_to_ensemble[
    (ncbi_to_ensemble["ensembl_gene"] != "-") &
    (ncbi_to_ensemble["geneid"].isin(all_ncbi_ids))
]

In [233]:
ncbi2ens_gene = (
    ncbi_to_ensemble_small
    .groupby(["taxid", "geneid"])["ensembl_gene"]
    .unique()
    .to_dict()
)
print(len(ncbi2ens_gene))

12528

In [234]:
import pickle
from functools import lru_cache

@lru_cache(maxsize=100_000)
def cached_ensembl_gene_to_rnacentral(ensembl_gene, taxid):
    return qrc.ensembl_gene_to_rnacentral_transcripts(ensembl_gene, taxid)

# -----------------------------
# Main function
# -----------------------------
errors_standard_types = []
errors_no_match_types = []
def get_rnacentral_from_ncbi_ids(row):
    """
    Starting from NCBI GeneIDs:
    - map to Ensembl transcripts via gene2ensembl
    - query RNAcentral at transcript level
    - enforce RNA type consistency
    - store list-of-lists in ID_buckets['RNAcentral']
      (one list per NCBI GeneID)
    - append to existing RNAcentral IDs if present
    """
    row = row.copy()   # critical
    id_buckets = row.get("ID_buckets", {})
    ncbi_ids = id_buckets.get("NCBI", [])
    taxid = str(row.get("Species"))
    row_rna_type = row.get("Category")  

    if not ncbi_ids or taxid is None:
        return row

    # skip existing RNAcentral entries, if any
    existing = id_buckets.get("RNAcentral", [])
    if existing:
        print(existing)
        print(id_buckets)
        return row
    rnacentral_per_ncbi = []

    for ncbi_id in ncbi_ids:
        rnacentral_ids = set()

        try:
            # NCBI GeneID → Ensembl Gene IDs
            ens_genes = ncbi2ens_gene.get((taxid, str(ncbi_id)), [])
            
            for ensembl_gene in ens_genes:
                #df = qrc.ensembl_gene_to_rnacentral_transcripts(
                #    ensembl_gene, taxid
                #)
                df = cached_ensembl_gene_to_rnacentral(ensembl_gene, taxid)

                if df is None or df.empty:
                    continue

                for _, r in df.iterrows():
                    rc_id = r.get("RNAcentral_ID") or r.get("rnacentral_id")
                    rc_type = r.get("rna_type")
                    
                    if pd.isna(rc_id) or pd.isna(rc_type):
                        continue

                    if rc_type not in STANDARD_RNA_TYPES:
                        errors_standard_types.append(f"[UNSTANDARDISED RNA TYPE] {rc_type} for row type {row_rna_type}")

                    if rc_type == row_rna_type:
                        rnacentral_ids.add(rc_id)
                    else:
                        errors_no_match_types.append(f"[no match RNA TYPE] {rc_type} for row type {row_rna_type}")

        except Exception:
            continue

        # Only append non-empty lists
        if rnacentral_ids:
            rnacentral_per_ncbi.append(list(rnacentral_ids))

    # If nothing found and no previous entries, make it empty
    id_buckets["RNAcentral"] = rnacentral_per_ncbi if rnacentral_per_ncbi else []
    row["ID_buckets"] = id_buckets

    return row

# -----------------------------
# Apply to dataframe
# -----------------------------

from tqdm import tqdm

tqdm.pandas(desc="Querying RNAcentral from NCBI IDs")

rna_entities_trial_stepTwo = rna_entities_trial.progress_apply(
    get_rnacentral_from_ncbi_ids,
    axis=1
)

# Save the counters to disk
with open("errors_standard_types.pkl", "wb") as f:
    pickle.dump(errors_standard_types, f)

with open("errors_no_match_types.pkl", "wb") as f:
    pickle.dump(errors_no_match_types, f)

'''
# Load them back later if needed
with open("errors_standard_types.pkl", "rb") as f:
    errors_standard_types_loaded = pickle.load(f)

with open("errors_no_match_types.pkl", "rb") as f:
    errors_no_match_types_loaded = pickle.load(f)
'''

Querying RNAcentral from NCBI IDs: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 29967/29967 [06:37<00:00, 75.31it/s]

In [176]:
import pandas as pd

rna_entities_trial_stepTwo.to_pickle("rna_entities_trial_stepTwo.pkl")

In [235]:
from collections import defaultdict

db_unique = defaultdict(set)

for buckets in rna_entities_trial_stepTwo["ID_buckets"]:
    for db, ids in buckets.items():

        # flatten list-of-lists
        for x in ids:
            if isinstance(x, list):
                db_unique[db].update(x)
            else:
                db_unique[db].add(x)

# Print summary
for db, ids in db_unique.items():
    print(f"{db}: {len(ids)} unique IDs across entities")

# 20492 from ENSEMBL IDS, so 74723 NEW IDS!!

from collections import defaultdict
import numpy as np

# Collect all IDs and lengths
db_unique = defaultdict(set)
db_lengths = defaultdict(list)

for buckets in rna_entities_trial_stepTwo["ID_buckets"]:
    for db, ids in buckets.items():
        for x in ids:
            if isinstance(x, list):
                db_unique[db].update(x)
                db_lengths[db].append(len(x))
            else:
                db_unique[db].add(x)
                db_lengths[db].append(1)

# Summary
for db, ids in db_unique.items():
    lengths = db_lengths[db]
    if lengths:
        max_len = max(lengths)
        mean_len = np.mean(lengths)
        median_len = np.median(lengths)
    else:
        max_len = mean_len = median_len = 0

    print(f"{db}: {len(ids)} unique IDs across entities | "
          f"max list length: {max_len}, mean: {mean_len:.2f}, median: {median_len}")


NC_RNA_TYPES = STANDARD_RNA_TYPES - {"mRNA"}

count_nc_only = 0
count_has_mrna = 0
count_no_rnacentral = 0
count_mrna_nornacentral = 0
count_ncRNA_noNCBI = 0

for _, row in rna_entities_trial_stepTwo.iterrows():
    rnacentral_ids = row["ID_buckets"]["RNAcentral"]
    # get RNA type
    rna_types = row.get("Category")
    if rna_types in NC_RNA_TYPES:
        if len(rnacentral_ids)>=1:
            count_nc_only += 1
            continue
        else:
            count_no_rnacentral += 1
            if row["ID_buckets"]["NCBI"]:
                count_ncRNA_noNCBI +=1
            continue
    else:
        if len(rnacentral_ids)>=1:
            count_has_mrna += 1
        else:
            count_mrna_nornacentral += 1

print("ncRNA-only entities:", count_nc_only)
print("entities with mRNA:", count_has_mrna)
print("entities without RNAcentral:", count_no_rnacentral)
print('count_mrna_nornacentral:', count_mrna_nornacentral)
print('count_ncRNA_noNCBI', count_ncRNA_noNCBI)

from collections import defaultdict

# Collect list lengths per database
db_lengths = defaultdict(list)

for buckets in rna_entities_trial_stepTwo["ID_buckets"]:
    for db, ids in buckets.items():
        for x in ids:
            if isinstance(x, list):
                db_lengths[db].append(len(x))
            else:
                db_lengths[db].append(1)

# Compute counts per category
for db, lengths in db_lengths.items():
    count_1 = sum(1 for l in lengths if l == 1)
    count_2 = sum(1 for l in lengths if l == 2)
    count_3_10 = sum(1 for l in lengths if 3 <= l <= 10)
    count_gt10 = sum(1 for l in lengths if l > 10)

    print(f"{db}: 1={count_1}, 2={count_2}, 3-10={count_3_10}, >10={count_gt10}")

Ensembl: 3886 unique IDs across entities
RNAcentral: 75893 unique IDs across entities
NCBI: 18622 unique IDs across entities
miRBase: 6365 unique IDs across entities
circBase: 206 unique IDs across entities
GenBank: 3 unique IDs across entities
tRFdb: 242 unique IDs across entities
Ensembl: 3886 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
RNAcentral: 75893 unique IDs across entities | max list length: 555, mean: 12.89, median: 3.0
NCBI: 18622 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
miRBase: 6365 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
circBase: 206 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
GenBank: 3 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
tRFdb: 242 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
ncRNA-only entities: 6217
entities with mRNA: 0
entities without RNAcentral: 23735
count_mrna_nornacentral: 15
count_ncRNA_noNCBI 14938

<h3>NCBI IDs to refSeq IDs to RNAcentral IDs</h3>

In [246]:
from collections import defaultdict
from functools import lru_cache

gene2refseq_index = defaultdict(list)

with open("gene2refseq", "r") as f:   # <-- FIX: no gzip
    for line in f:
        if line.startswith("#"):
            continue
        cols = line.rstrip("\n").split("\t")

        taxid = cols[0]
        geneid = cols[1]
        rna_acc = cols[3]   # RNA_nucleotide_accession
        status = cols[2]

        if status == "SUPPRESSED":
            continue

        if rna_acc == "-":
            continue

        if rna_acc.startswith(("NR_", "XR_")):
            rna_type = "ncRNA"
        #elif rna_acc.startswith(("NM_", "XM_")):
        #    continue
            #rna_type = "mRNA"
        else:
            continue

        gene2refseq_index[(taxid, geneid)].append({
            "refseq_id": rna_acc,
            "rna_type": rna_type,
            "status": status
        })

In [267]:
@lru_cache(maxsize=100_000)
def ncbi_gene_to_refseq_transcripts(ncbi_gene_id, taxid):
    key = (str(ncbi_gene_id), str(taxid))  # cast to str
    return gene2refseq_index.get(key, [])

ncbi_gene_to_refseq_transcripts(2711, 102577949)

[{'refseq_id': 'XR_003065960.2', 'rna_type': 'ncRNA', 'status': 'MODEL'},
 {'refseq_id': 'XR_371036.4', 'rna_type': 'ncRNA', 'status': 'MODEL'}]

In [249]:
refseq_id = "NR_036832"  # example RefSeq
taxid = "58123"
print(f"\nRefSeq to RNAcentral (RefSeq={refseq_id}, taxid={taxid}):")
df_ref = qrc.refseq_to_rnacentral(refseq_id, taxid)
print(df_ref)

RefSeq to RNAcentral (RefSeq=NR_036832, taxid=58123):
   RNAcentral_ID rna_type
0  URS0000000036     rRNA

In [282]:

errors_standard_types = []
errors_no_match_types = []

def get_rnacentral_from_ncbi_ids_refseq(row):
    row = row.copy()
    id_buckets = row.get("ID_buckets", {})
    ncbi_ids = id_buckets.get("NCBI", [])
    taxid = str(row.get("Species"))
    row_rna_type = row.get("Category")

    if not ncbi_ids or not taxid:
        return row

    # do not overwrite existing RNAcentral mappings
    if id_buckets.get("RNAcentral"):
        return row

    rnacentral_per_ncbi = []

    for ncbi_id in ncbi_ids:
        rnacentral_ids = set()
        try:
            refseq_records = ncbi_gene_to_refseq_transcripts(
                taxid, ncbi_id
            )
            if not refseq_records:
                continue
            #print('taxid', taxid)
            #print('ncbi_id', ncbi_id)
            #print('refseq_records', refseq_records)

            for rec in refseq_records:
                refseq_id = rec.get("refseq_id")
                refseq_id = refseq_id.split(".")[0]
                status = rec.get("status")
                #print('refseq_id', refseq_id)

                if not refseq_id:
                    continue

                df_rnacentral = qrc.refseq_to_rnacentral(str(refseq_id), str(taxid))

                if df_rnacentral is None or df_rnacentral.empty:
                    continue
                
                # For loop for Rnacentral items:
                for _, row_rc in df_rnacentral.iterrows():
                    rnacentral_id = row_rc.get('RNAcentral_ID')
                    rc_type = row_rc.get('rna_type')
                    #print('rnacentral_id', rnacentral_id)
                    #print('rc_type', rc_type)
                    #print('row_rna_type', row_rna_type)

                    if rc_type not in STANDARD_RNA_TYPES:
                        errors_standard_types.append(
                            f"[UNSTANDARDISED RNA TYPE] {rc_type} (refseq_id:{refseq_id})"
                        )

                    if rc_type == row_rna_type:
                        rnacentral_ids.add(rnacentral_id)
                    else:
                        errors_no_match_types.append(
                            f"[NO MATCH RNA TYPE] {rc_type} vs {row_rna_type} (refseq_id:{refseq_id})"
                        )

        except Exception as e:
            print("Error:", e)
            continue

        if rnacentral_ids:
            rnacentral_per_ncbi.append(list(rnacentral_ids))

    id_buckets["RNAcentral"] = rnacentral_per_ncbi
    row["ID_buckets"] = id_buckets
    return row


rna_entities_trial_stepThree = rna_entities_trial_stepTwo.progress_apply(
    get_rnacentral_from_ncbi_ids_refseq,
    axis=1
)

Querying RNAcentral from NCBI IDs: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 29967/29967 [07:03<00:00, 70.77it/s]

In [17]:
from collections import defaultdict

db_unique = defaultdict(set)

for buckets in rna_entities_trial_stepThree["ID_buckets"]:
    for db, ids in buckets.items():

        # flatten list-of-lists
        for x in ids:
            if isinstance(x, list):
                db_unique[db].update(x)
            else:
                db_unique[db].add(x)

# Print summary
for db, ids in db_unique.items():
    print(f"{db}: {len(ids)} unique IDs across entities")

# 20492 from ENSEMBL IDS, so 74723 NEW IDS!!

from collections import defaultdict
import numpy as np

# Collect all IDs and lengths
db_unique = defaultdict(set)
db_lengths = defaultdict(list)

for buckets in rna_entities_trial_stepThree["ID_buckets"]:
    for db, ids in buckets.items():
        for x in ids:
            if isinstance(x, list):
                db_unique[db].update(x)
                db_lengths[db].append(len(x))
            else:
                db_unique[db].add(x)
                db_lengths[db].append(1)

# Summary
for db, ids in db_unique.items():
    lengths = db_lengths[db]
    if lengths:
        max_len = max(lengths)
        mean_len = np.mean(lengths)
        median_len = np.median(lengths)
    else:
        max_len = mean_len = median_len = 0

    print(f"{db}: {len(ids)} unique IDs across entities | "
          f"max list length: {max_len}, mean: {mean_len:.2f}, median: {median_len}")


NC_RNA_TYPES = STANDARD_RNA_TYPES - {"mRNA"}

count_nc_only = 0
count_has_mrna = 0
count_no_rnacentral = 0
count_mrna_nornacentral = 0
count_ncRNA_noNCBI = 0

for _, row in rna_entities_trial_stepThree.iterrows():
    rnacentral_ids = row["ID_buckets"]["RNAcentral"]
    # get RNA type
    rna_types = row.get("Category")
    if rna_types in NC_RNA_TYPES:
        if len(rnacentral_ids)>=1:
            count_nc_only += 1
            continue
        else:
            count_no_rnacentral += 1
            if row["ID_buckets"]["NCBI"]:
                count_ncRNA_noNCBI +=1
            continue
    else:
        if len(rnacentral_ids)>=1:
            count_has_mrna += 1
        else:
            count_mrna_nornacentral += 1

print("ncRNA-only entities:", count_nc_only)
print("entities with mRNA:", count_has_mrna)
print("entities without RNAcentral:", count_no_rnacentral)
print('count_mrna_nornacentral:', count_mrna_nornacentral)
print('count_ncRNA_noNCBI', count_ncRNA_noNCBI)

from collections import defaultdict

# Collect list lengths per database
db_lengths = defaultdict(list)

for buckets in rna_entities_trial_stepThree["ID_buckets"]:
    for db, ids in buckets.items():
        for x in ids:
            if isinstance(x, list):
                db_lengths[db].append(len(x))
            else:
                db_lengths[db].append(1)

# Compute counts per category
for db, lengths in db_lengths.items():
    count_1 = sum(1 for l in lengths if l == 1)
    count_2 = sum(1 for l in lengths if l == 2)
    count_3_10 = sum(1 for l in lengths if 3 <= l <= 10)
    count_gt10 = sum(1 for l in lengths if l > 10)

    print(f"{db}: 1={count_1}, 2={count_2}, 3-10={count_3_10}, >10={count_gt10}")

Ensembl: 3886 unique IDs across entities
RNAcentral: 77590 unique IDs across entities
NCBI: 18622 unique IDs across entities
miRBase: 6365 unique IDs across entities
circBase: 206 unique IDs across entities
GenBank: 3 unique IDs across entities
tRFdb: 242 unique IDs across entities
Ensembl: 3886 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
RNAcentral: 77590 unique IDs across entities | max list length: 555, mean: 10.70, median: 2.0
NCBI: 18622 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
miRBase: 6365 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
circBase: 206 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
GenBank: 3 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
tRFdb: 242 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
ncRNA-only entities: 7656
entities with mRNA: 0
entities without RNAcentral: 22296
count_mrna_nornacentral: 15
count_ncRNA_noNCBI 13499
Ensembl: 1=3886, 2=0, 3-10=0, >10=0
RNAcentral: 1=3726, 2=658, 3-10=1497, >10=1775
NCBI: 1=19037, 2=0, 3-10=0, >10=0
miRBase: 1=6547, 2=0, 3-10=0, >10=0
circBase: 1=255, 2=0, 3-10=0, >10=0
GenBank: 1=3, 2=0, 3-10=0, >10=0
tRFdb: 1=261, 2=0, 3-10=0, >10=0

In [306]:

rna_entities_trial_stepThree.to_pickle("rna_entities_trial_stepThree.pkl")

<h3>miRbase IDs to mature miRbase IDs to RNAcentral IDs (TODO)</h3>

In [16]:
import pandas as pd
rna_entities_trial_stepThree = pd.read_pickle("rna_entities_trial_stepThree.pkl")

In [3]:
import pandas as pd

STANDARD_RNA_TYPES = {
    "tRNA", "miRNA", "rRNA", "pseudo", "lncRNA", "piRNA", "tRF", "mRNA",
    "sRNA", "lincRNA", "circRNA", "ncRNA", "ribozyme", "snoRNA",
    "scaRNA", "snRNA", "scRNA", "sncRNA"
}

# Construct DUCK-DB based on RNAcentral BEFORE this step!!
import sys
sys.path.append("rnacentral-etl")

from rnacentral import QueryRnaCentral

qrc = QueryRnaCentral(base_dir="rnacentral_data/current_release", db_path="rnacentral-etl/rnacentral.duckdb")

In [9]:
qrc.mirbase_to_rnacentral('MIMAT0000434', '9606')

   RNAcentral_ID rna_type  taxid
0  URS00002620A7    miRNA   9606

In [10]:
from Bio import SeqIO
from collections import defaultdict

# precursor_id -> list of mature IDs (MIMAT…)
precursor_to_mature_ids = defaultdict(list)

# mature_id -> sequence
mature_to_sequence = defaultdict(list)

# precursor_id -> fallback sequences
precursor_to_sequence = defaultdict(list)

for record in SeqIO.parse("miRNA.dat", "embl"):
    precursor_id = record.id  # MI000...

    for feature in record.features:
        if feature.type not in ("miRNA", "mature_miRNA"):
            continue

        seq = feature.location.extract(record).seq.upper().replace("T", "U")
        quals = feature.qualifiers

        mat_acc = quals.get("accession", [None])[0]

        if mat_acc:  # mature miRNA
            mature_to_sequence[mat_acc].append(str(seq))
            precursor_to_mature_ids[precursor_id].append(mat_acc)
        else:
            # precursor-only sequence (fallback)
            precursor_to_sequence[precursor_id].append(str(seq))

In [13]:
def get_mirna_sequences(row):
    row = row.copy()
    id_buckets = row.get("ID_buckets", {})
    taxid = str(row.get("Species"))

    mirbase_ids = id_buckets.get("miRBase", [])
    rnacentral_per_mirbase = []
    seqs = set()

    if not mirbase_ids:
        return row

    rnacentral_ids = set()

    for mid in mirbase_ids:
        mature_ids = []

        if mid.startswith("MIMAT"):
            mature_ids = [mid]
        else:
            # precursor → mature IDs
            mature_ids = precursor_to_mature_ids.get(mid, [])

            # fallback: no mature annotated
            if not mature_ids:
                seqs.update(precursor_to_sequence.get(mid, []))
                continue

        for mature_id in mature_ids:
            # sequences
            seqs.update(mature_to_sequence.get(mature_id, []))

            # RNAcentral mapping
            df_rc = qrc.mirbase_to_rnacentral(mature_id, taxid)
            if df_rc is not None and not df_rc.empty:
                rnacentral_ids.update(df_rc["RNAcentral_ID"].tolist())

    if rnacentral_ids:
        rnacentral_per_mirbase.append(list(rnacentral_ids))

    row["sequences"] = list(seqs)
    id_buckets["RNAcentral"] = rnacentral_per_mirbase
    row["ID_buckets"] = id_buckets

    return row

In [14]:
rna_entities_trial_stepFour = rna_entities_trial_stepThree.apply(
    get_mirna_sequences, axis=1
)

In [15]:
from collections import defaultdict

db_unique = defaultdict(set)

for buckets in rna_entities_trial_stepFour["ID_buckets"]:
    for db, ids in buckets.items():

        # flatten list-of-lists
        for x in ids:
            if isinstance(x, list):
                db_unique[db].update(x)
            else:
                db_unique[db].add(x)

# Print summary
for db, ids in db_unique.items():
    print(f"{db}: {len(ids)} unique IDs across entities")

# 20492 from ENSEMBL IDS, so 74723 NEW IDS!!

from collections import defaultdict
import numpy as np

# Collect all IDs and lengths
db_unique = defaultdict(set)
db_lengths = defaultdict(list)

for buckets in rna_entities_trial_stepFour["ID_buckets"]:
    for db, ids in buckets.items():
        for x in ids:
            if isinstance(x, list):
                db_unique[db].update(x)
                db_lengths[db].append(len(x))
            else:
                db_unique[db].add(x)
                db_lengths[db].append(1)

# Summary
for db, ids in db_unique.items():
    lengths = db_lengths[db]
    if lengths:
        max_len = max(lengths)
        mean_len = np.mean(lengths)
        median_len = np.median(lengths)
    else:
        max_len = mean_len = median_len = 0

    print(f"{db}: {len(ids)} unique IDs across entities | "
          f"max list length: {max_len}, mean: {mean_len:.2f}, median: {median_len}")


NC_RNA_TYPES = STANDARD_RNA_TYPES - {"mRNA"}

count_nc_only = 0
count_has_mrna = 0
count_no_rnacentral = 0
count_mrna_nornacentral = 0
count_ncRNA_noNCBI = 0

for _, row in rna_entities_trial_stepFour.iterrows():
    rnacentral_ids = row["ID_buckets"]["RNAcentral"]
    # get RNA type
    rna_types = row.get("Category")
    if rna_types in NC_RNA_TYPES:
        if len(rnacentral_ids)>=1:
            count_nc_only += 1
            continue
        else:
            count_no_rnacentral += 1
            if row["ID_buckets"]["NCBI"]:
                count_ncRNA_noNCBI +=1
            continue
    else:
        if len(rnacentral_ids)>=1:
            count_has_mrna += 1
        else:
            count_mrna_nornacentral += 1

print("ncRNA-only entities:", count_nc_only)
print("entities with mRNA:", count_has_mrna)
print("entities without RNAcentral:", count_no_rnacentral)
print('count_mrna_nornacentral:', count_mrna_nornacentral)
print('count_ncRNA_noNCBI', count_ncRNA_noNCBI)

from collections import defaultdict

# Collect list lengths per database
db_lengths = defaultdict(list)

for buckets in rna_entities_trial_stepFour["ID_buckets"]:
    for db, ids in buckets.items():
        for x in ids:
            if isinstance(x, list):
                db_lengths[db].append(len(x))
            else:
                db_lengths[db].append(1)

# Compute counts per category
for db, lengths in db_lengths.items():
    count_1 = sum(1 for l in lengths if l == 1)
    count_2 = sum(1 for l in lengths if l == 2)
    count_3_10 = sum(1 for l in lengths if 3 <= l <= 10)
    count_gt10 = sum(1 for l in lengths if l > 10)

    print(f"{db}: 1={count_1}, 2={count_2}, 3-10={count_3_10}, >10={count_gt10}")

Ensembl: 3886 unique IDs across entities
RNAcentral: 82307 unique IDs across entities
NCBI: 18622 unique IDs across entities
miRBase: 6365 unique IDs across entities
circBase: 206 unique IDs across entities
GenBank: 3 unique IDs across entities
tRFdb: 242 unique IDs across entities
Ensembl: 3886 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
RNAcentral: 82307 unique IDs across entities | max list length: 555, mean: 6.33, median: 1.0
NCBI: 18622 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
miRBase: 6365 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
circBase: 206 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
GenBank: 3 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
tRFdb: 242 unique IDs across entities | max list length: 1, mean: 1.00, median: 1.0
ncRNA-only entities: 14072
entities with mRNA: 0
entities without RNAcentral: 15880
count_mrna_nornacentral: 15
count_ncRNA_noNCBI 13499
Ensembl: 1=3886, 2=0, 3-10=0, >10=0
RNAcentral: 1=9447, 2=1343, 3-10=1507, >10=1775
NCBI: 1=19037, 2=0, 3-10=0, >10=0
miRBase: 1=6547, 2=0, 3-10=0, >10=0
circBase: 1=255, 2=0, 3-10=0, >10=0
GenBank: 1=3, 2=0, 3-10=0, >10=0
tRFdb: 1=261, 2=0, 3-10=0, >10=0

In [19]:
count_seq = 0
count_noseq = 0
for idx, row in rna_entities_trial_stepFour.iterrows():
    rna_lists = row.get("ID_buckets", {}).get("RNAcentral", [])
    if rna_lists:  # only non-empty rows
        count_seq += 1
    else:
        count_noseq +=1

In [20]:
count_seq

14072

In [21]:
count_noseq

15895

In [ ]:
# 1. retrieve RNAcentral sequences: rnacentral_to_sequence
# 2. retrieve GO terms with rnacentral_metadata

In [64]:
# NOW THAT WE HAVE ALL THE IDS AND CORRESPONDING SEQUENCES,
# WE count/Drop rows with missing sequences

df_expanded = df_expanded.dropna(subset=["seq1", "seq2"])
df_expanded = df_expanded[(df_expanded["seq1"] != "") & (df_expanded["seq2"] != "")]
print(len(df_expanded))

3042